description "Electron Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env ELECTROND_BIN="/usr/bin/electrond"
env ELECTROND_USER="electron"
env ELECTROND_GROUP="electron"
env ELECTROND_PIDDIR="/var/run/electrond"
# upstart can't handle variables constructed with other variables
env ELECTROND_PIDFILE="/var/run/electrond/electrond.pid"
env ELECTROND_CONFIGFILE="/etc/electron/electron.conf"
env ELECTROND_DATADIR="/var/lib/electrond"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # electrond will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$ELECTROND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run electrond."
        echo "The setting must appear in $ELECTROND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Electron Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$ELECTROND_PIDDIR"
    chmod 0755 "$ELECTROND_PIDDIR"
    chown $ELECTROND_USER:$ELECTROND_GROUP "$ELECTROND_PIDDIR"
    chown $ELECTROND_USER:$ELECTROND_GROUP "$ELECTROND_CONFIGFILE"
    chmod 0660 "$ELECTROND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$ELECTROND_PIDFILE" \
    --chuid $ELECTROND_USER:$ELECTROND_GROUP \
    --exec "$ELECTROND_BIN" \
    -- \
    -pid="$ELECTROND_PIDFILE" \
    -conf="$ELECTROND_CONFIGFILE" \
    -datadir="$ELECTROND_DATADIR" \
    -disablewallet \
    -daemon
